GRANT USAGE ON SCHEMA agency,auth TO agency_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA agency TO agency_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA agency GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO agency_app;
