BEGIN;
CREATE OR REPLACE FUNCTION agency.customer_localize_email_queue(p_tenant uuid,p_email text,p_lang text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ DECLARE subject text; prefix text; suffix text; BEGIN
 subject:=CASE p_lang WHEN 'en' THEN 'Your verification code' WHEN 'de' THEN 'Ihr Bestätigungscode' WHEN 'ru' THEN 'Ваш код подтверждения' WHEN 'fr' THEN 'Votre code de vérification' WHEN 'zh' THEN '您的验证码' ELSE 'Doğrulama kodunuz' END;
 prefix:=CASE p_lang WHEN 'en' THEN 'Verification code: ' WHEN 'de' THEN 'Bestätigungscode: ' WHEN 'ru' THEN 'Код подтверждения: ' WHEN 'fr' THEN 'Code de vérification : ' WHEN 'zh' THEN '验证码：' ELSE 'Doğrulama kodunuz: ' END;
 suffix:=CASE p_lang WHEN 'en' THEN 'Valid for 10 minutes. Do not share this code.' WHEN 'de' THEN '10 Minuten gültig. Teilen Sie diesen Code nicht.' WHEN 'ru' THEN 'Действителен 10 минут. Не сообщайте этот код другим.' WHEN 'fr' THEN 'Valide 10 minutes. Ne partagez pas ce code.' WHEN 'zh' THEN '有效期10分钟，请勿分享验证码。' ELSE 'Kod 10 dakika geçerlidir. Bu kodu paylaşmayın.' END;
 UPDATE agency.notifications n SET payload=n.payload||jsonb_build_object('subject',subject,'html','<p>'||prefix||'<strong>'||substring(n.payload->>'html' FROM '<strong>([0-9]{8})</strong>')||'</strong></p><p>'||suffix||'</p>') FROM agency.users u WHERE n.tenant_id=p_tenant AND n.user_id=u.id AND u.tenant_id=p_tenant AND lower(u.email)=lower(trim(p_email)) AND n.status='queued' AND n.template IN ('customer.auth.email','customer.auth.reset','customer.auth.email_change') AND n.created_at>now()-interval '1 minute' AND n.payload->>'html' ~ '<strong>[0-9]{8}</strong>';
 END $$;
CREATE OR REPLACE FUNCTION agency.customer_register_localized(p_tenant uuid,p_name text,p_email text,p_phone text,p_password text,p_terms boolean,p_lang text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ DECLARE r text; BEGIN r:=agency.customer_register(p_tenant,p_name,p_email,p_phone,p_password,p_terms); IF r='accepted' THEN PERFORM agency.customer_localize_email_queue(p_tenant,p_email,p_lang); END IF; RETURN r; END $$;
CREATE OR REPLACE FUNCTION agency.customer_request_localized(p_tenant uuid,p_email text,p_purpose text,p_channel text,p_lang text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ DECLARE r text; BEGIN r:=agency.customer_auth_request(p_tenant,p_email,p_purpose,p_channel); IF r='accepted' THEN PERFORM agency.customer_localize_email_queue(p_tenant,p_email,p_lang); END IF; RETURN r; END $$;
CREATE OR REPLACE FUNCTION agency.customer_contact_request_localized(p_tenant uuid,p_user uuid,p_kind text,p_target text,p_password text,p_lang text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ DECLARE r text; BEGIN r:=agency.customer_contact_request(p_tenant,p_user,p_kind,p_target,p_password); IF r='accepted' THEN PERFORM agency.customer_localize_email_queue(p_tenant,(SELECT email FROM agency.users WHERE id=p_user AND tenant_id=p_tenant),p_lang); END IF; RETURN r; END $$;
REVOKE ALL ON FUNCTION agency.customer_localize_email_queue(uuid,text,text),agency.customer_register_localized(uuid,text,text,text,text,boolean,text),agency.customer_request_localized(uuid,text,text,text,text),agency.customer_contact_request_localized(uuid,uuid,text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION agency.customer_register_localized(uuid,text,text,text,text,boolean,text),agency.customer_request_localized(uuid,text,text,text,text),agency.customer_contact_request_localized(uuid,uuid,text,text,text,text) TO agency_app;
CREATE OR REPLACE FUNCTION agency.customer_expire_email_codes() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ BEGIN
 UPDATE agency.notifications n SET payload=(n.payload-'html')||jsonb_build_object('html','<p>Verification code expired.</p>'),status=CASE WHEN n.status='queued' THEN 'failed' ELSE n.status END WHERE n.template IN ('customer.auth.email','customer.auth.reset','customer.auth.email_change') AND n.payload->>'html' ~ '<strong>[0-9]{8}</strong>' AND (n.created_at<=now()-interval '10 minutes' OR EXISTS(SELECT 1 FROM agency.customer_auth_challenges c WHERE c.tenant_id=n.tenant_id AND c.user_id=n.user_id AND c.purpose=substring(n.template FROM 15) AND c.consumed_at IS NOT NULL AND c.created_at=n.created_at));
 END $$;
REVOKE ALL ON FUNCTION agency.customer_expire_email_codes() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION agency.customer_expire_email_codes() TO agency_app;
COMMIT;
