BEGIN;
ALTER TABLE agency.customer_phone_outbox ADD COLUMN IF NOT EXISTS provider_message_id text;
ALTER TABLE agency.customer_phone_outbox ADD COLUMN IF NOT EXISTS delivery_status text NOT NULL DEFAULT 'pending' CHECK(delivery_status IN ('pending','accepted','delivered','read','failed'));
ALTER TABLE agency.customer_phone_outbox ADD COLUMN IF NOT EXISTS delivered_at timestamptz;
CREATE UNIQUE INDEX IF NOT EXISTS customer_phone_provider_id ON agency.customer_phone_outbox(provider_message_id) WHERE provider_message_id IS NOT NULL;
CREATE OR REPLACE FUNCTION agency.customer_phone_accept(p_id uuid,p_provider text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ BEGIN
 IF coalesce(p_provider,'')='' OR length(p_provider)>255 THEN RETURN 'invalid'; END IF;
 UPDATE agency.customer_phone_outbox SET provider_message_id=p_provider,delivery_status='accepted' WHERE id=p_id AND status='sending';
 RETURN 'accepted'; END $$;
CREATE OR REPLACE FUNCTION agency.customer_phone_delivery(p_tenant uuid,p_phone_id text,p_id text,p_status text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ BEGIN
 IF p_status NOT IN ('sent','delivered','read','failed') OR length(p_id)>255 OR NOT EXISTS(SELECT 1 FROM agency.integrations WHERE tenant_id=p_tenant AND active AND provider='sms_whatsapp' AND kind='notification' AND credentials->>'whatsapp_phone_id'=p_phone_id) THEN RETURN false; END IF;
 UPDATE agency.customer_phone_outbox SET delivery_status=CASE WHEN p_status='sent' THEN 'accepted' ELSE p_status END, delivered_at=CASE WHEN p_status IN ('delivered','read') THEN coalesce(delivered_at,now()) ELSE delivered_at END, error_code=CASE WHEN p_status='failed' THEN 'delivery_failed' ELSE error_code END
 WHERE tenant_id=p_tenant AND provider_message_id=p_id AND delivery_status<>'read' AND (delivery_status<>'delivered' OR p_status='read') AND (delivery_status<>'failed' OR p_status IN ('delivered','read'));
 RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION agency.customer_phone_delivery_state(p_tenant uuid,p_user uuid) RETURNS text LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ SELECT coalesce((SELECT CASE WHEN o.delivery_status IN ('delivered','read','failed') THEN o.delivery_status ELSE o.status END FROM agency.customer_phone_outbox o JOIN agency.users u ON u.id=o.user_id AND u.tenant_id=o.tenant_id JOIN agency.customer_auth_challenges c ON c.id=o.challenge_id WHERE o.tenant_id=p_tenant AND o.user_id=p_user AND u.membership_type='customer' ORDER BY c.created_at DESC,o.id DESC LIMIT 1),'') $$;
CREATE OR REPLACE FUNCTION agency.membership_setup_data(p_tenant uuid,p_user uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ DECLARE s jsonb; i jsonb; BEGIN
 IF NOT EXISTS(SELECT 1 FROM agency.users WHERE id=p_user AND tenant_id=p_tenant AND membership_type='admin' AND active) THEN RETURN '{}'::jsonb; END IF;
 SELECT coalesce(jsonb_object_agg(key,value),'{}') INTO s FROM agency.settings WHERE tenant_id=p_tenant;
 SELECT credentials INTO i FROM agency.integrations WHERE tenant_id=p_tenant AND provider='sms_whatsapp' AND kind='notification' AND active LIMIT 1;
 RETURN jsonb_build_object('tenant',p_tenant,'smtp',coalesce(s->>'smtp_host','')<>'' AND coalesce(s->>'smtp_username','')<>'' AND coalesce(s->>'smtp_from','')<>'' AND (coalesce(s->>'smtp_password_sealed','')<>'' OR coalesce(s->>'smtp_password','')<>''),'whatsapp',coalesce(i->>'whatsapp_phone_id','')~'^[0-9]{5,30}$' AND coalesce(i->>'whatsapp_token_sealed','')<>'' AND coalesce(s->>'whatsapp_auth_template','')~'^[a-z0-9_]+$' AND coalesce(s->>'whatsapp_auth_language','')~'^[a-z]{2,3}(_[A-Z]{2})?$' AND coalesce(s->>'whatsapp_api_version','')~'^v[0-9]{1,2}\.[0-9]$','webhook',coalesce(s->>'membership_whatsapp_app_secret_sealed','')<>'' AND coalesce(s->>'membership_whatsapp_verify_token_sealed','')<>'','legal',length(trim(coalesce(s->>'contract_membership','')))>0 AND length(trim(coalesce(s->>'contract_privacy_policy','')))>0,'mfa',exists(SELECT 1 FROM agency.admin_mfa WHERE tenant_id=p_tenant AND user_id=p_user AND enabled),'pendingIdentity',(SELECT count(*) FROM agency.customer_verification WHERE tenant_id=p_tenant AND identity_status='pending' AND submitted_at IS NOT NULL),'email',(SELECT email FROM agency.users WHERE id=p_user),'tests',coalesce((SELECT jsonb_agg(x) FROM (SELECT id::text,channel,status,delivery_status,created_at::text FROM agency.notifications WHERE tenant_id=p_tenant AND template='membership.connection.test' ORDER BY created_at DESC LIMIT 10) x),'[]'::jsonb),'phoneTests',coalesce((SELECT jsonb_agg(x) FROM (SELECT o.id::text,o.status,o.delivery_status,o.updated_at::text FROM agency.customer_phone_outbox o JOIN agency.users u ON u.id=o.user_id WHERE o.tenant_id=p_tenant AND u.membership_type='admin' ORDER BY o.updated_at DESC LIMIT 10) x),'[]'::jsonb),'alerts',coalesce((SELECT jsonb_agg(x) FROM (SELECT 'email' AS channel,id::text,status,created_at::text FROM agency.notifications WHERE tenant_id=p_tenant AND status='failed' AND template LIKE 'customer.%' UNION ALL SELECT 'whatsapp',id::text,CASE WHEN delivery_status='failed' THEN 'delivery_failed' ELSE status END,updated_at::text FROM agency.customer_phone_outbox WHERE tenant_id=p_tenant AND (status='failed' OR delivery_status='failed') ORDER BY created_at DESC LIMIT 30) x),'[]'::jsonb));
 END $$;
CREATE OR REPLACE FUNCTION agency.membership_connection_test(p_tenant uuid,p_user uuid,p_channel text,p_target text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,agency AS $$ DECLARE setup jsonb; code text; challenge uuid; BEGIN
 setup:=agency.membership_setup_data(p_tenant,p_user); IF setup='{}'::jsonb THEN RETURN 'forbidden'; END IF;
 PERFORM pg_advisory_xact_lock(hashtext(p_tenant::text||'membership_test'));
 IF EXISTS(SELECT 1 FROM agency.notifications WHERE tenant_id=p_tenant AND template='membership.connection.test' AND created_at>now()-interval '1 minute') OR EXISTS(SELECT 1 FROM agency.customer_phone_outbox o JOIN agency.customer_auth_challenges c ON c.id=o.challenge_id JOIN agency.users u ON u.id=o.user_id WHERE o.tenant_id=p_tenant AND u.membership_type='admin' AND c.created_at>now()-interval '1 minute') THEN RETURN 'rate_limited'; END IF;
 IF p_channel='email' THEN
 IF NOT (setup->>'smtp')::boolean THEN RETURN 'provider_unavailable'; END IF;
 -- Only send to the signed-in administrator, never an arbitrary public recipient.
 IF lower(trim(p_target))<>lower(setup->>'email') THEN RETURN 'own_email_required'; END IF;
 INSERT INTO agency.notifications(tenant_id,user_id,channel,template,payload,status) VALUES(p_tenant,p_user,'email','membership.connection.test',jsonb_build_object('to',p_target,'email',p_target,'subject','NEXUS bağlantı testi','html','<p>Bu e-posta, yönetim panelinden başlattığınız bağlantı testidir.</p>'),'queued'); RETURN 'queued';
 ELSIF p_channel='whatsapp' THEN
 IF NOT (setup->>'whatsapp')::boolean THEN RETURN 'provider_unavailable'; END IF;
 IF p_target !~ '^\+[1-9][0-9]{7,14}$' THEN RETURN 'invalid_phone'; END IF;
 code:=lpad((get_byte(gen_random_bytes(1),0)*65536+get_byte(gen_random_bytes(1),0)*256+get_byte(gen_random_bytes(1),0))::text,8,'0');
 INSERT INTO agency.customer_auth_challenges(tenant_id,user_id,purpose,channel,code_hash,expires_at) VALUES(p_tenant,p_user,'phone','whatsapp',encode(digest(code,'sha256'),'hex'),now()+interval '10 minutes') RETURNING id INTO challenge;
 INSERT INTO agency.customer_phone_outbox(tenant_id,user_id,challenge_id,phone,code) VALUES(p_tenant,p_user,challenge,p_target,code); RETURN 'queued';
 END IF; RETURN 'invalid'; END $$;
REVOKE ALL ON FUNCTION agency.customer_phone_accept(uuid,text),agency.customer_phone_delivery(uuid,text,text,text),agency.membership_setup_data(uuid,uuid),agency.membership_connection_test(uuid,uuid,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION agency.customer_phone_accept(uuid,text),agency.customer_phone_delivery(uuid,text,text,text),agency.membership_setup_data(uuid,uuid),agency.membership_connection_test(uuid,uuid,text,text) TO agency_app;
COMMIT;
