-- Canonical category field catalog backfill (fresh-install gap fix).
--
-- On a fresh installation the tenant-referencing field seeds run before any
-- tenant exists (030) and the later copy-based migrations (085) can only
-- duplicate rows that already exist somewhere. The result was a 21-field
-- catalog instead of the full 106-field canonical contract, which broke
-- listing validation (wp1), new-tenant bootstrap parity
-- (tenant_catalog_bootstrap) and every contract-field surface.
--
-- Source of truth: the deployed contract (085's allowed set == 106 pairs,
-- with label/field_type/required/options/sort_order as deployed). Rows are
-- inserted for every tenant's canonical parent categories; existing rows are
-- never modified (ON CONFLICT DO NOTHING), matching seed_tenant_catalog
-- semantics: only missing rows are copied, tenant display choices stay
-- independent.
INSERT INTO agency.category_fields(category_id, field_key, label, field_type, required, options, sort_order)
SELECT target.id, v.field_key, v.label, v.field_type, v.required, v.options, v.sort_order
FROM (VALUES
  ('activity', 'activity_type', 'Aktivite türü', 'select', true, '["Spor", "Doğa", "Eğlence", "Workshop", "Adrenalin", "Kültür"]'::jsonb, 10),
  ('activity', 'duration', 'Süre', 'text', true, '[]'::jsonb, 20),
  ('activity', 'difficulty', 'Zorluk', 'select', false, '["Kolay", "Orta", "Zor", "Profesyonel"]'::jsonb, 30),
  ('activity', 'age_limit', 'Yaş sınırı', 'text', false, '[]'::jsonb, 40),
  ('activity', 'equipment_included', 'Ekipman dahil', 'boolean', false, '[]'::jsonb, 50),
  ('activity', 'meeting_point', 'Buluşma noktası', 'text', true, '[]'::jsonb, 60),
  ('beach', 'beach_name', 'Plaj adı', 'text', true, '[]'::jsonb, 10),
  ('beach', 'access_type', 'Erişim tipi', 'select', true, '["Günübirlik", "Üyelik", "Rezervasyonlu", "Özel Alan"]'::jsonb, 20),
  ('beach', 'seat_type', 'Ünite tipi', 'select', true, '["Şezlong", "Şemsiye", "Loca", "Daybed", "Kabana"]'::jsonb, 30),
  ('beach', 'capacity', 'Kapasite', 'number', true, '[]'::jsonb, 40),
  ('beach', 'food_beverage_policy', 'Yeme içme politikası', 'text', false, '[]'::jsonb, 50),
  ('beach', 'time_slot', 'Zaman dilimi', 'text', true, '[]'::jsonb, 60),
  ('bus', 'operator', 'Operatör', 'text', true, '[]'::jsonb, 10),
  ('bus', 'route_from', 'Kalkış noktası', 'text', true, '[]'::jsonb, 20),
  ('bus', 'route_to', 'Varış noktası', 'text', true, '[]'::jsonb, 30),
  ('bus', 'seat_type', 'Koltuk tipi', 'text', false, '[]'::jsonb, 40),
  ('bus', 'baggage_policy', 'Bagaj politikası', 'text', true, '[]'::jsonb, 50),
  ('bus', 'ticket_rules', 'Bilet kuralları', 'text', true, '[]'::jsonb, 60),
  ('car', 'vehicle_type', 'Araç tipi', 'select', true, '["Ekonomi", "Orta", "Üst Segment", "SUV", "Minivan", "Minibüs", "Lüks"]'::jsonb, 10),
  ('car', 'brand_model', 'Marka / model', 'text', false, '[]'::jsonb, 20),
  ('car', 'transmission', 'Vites', 'select', true, '["Otomatik", "Manuel"]'::jsonb, 30),
  ('car', 'fuel_type', 'Yakıt tipi', 'select', false, '["Benzin", "Dizel", "Hibrit", "Elektrik", "LPG"]'::jsonb, 40),
  ('car', 'seat_count', 'Koltuk sayısı', 'number', true, '[]'::jsonb, 50),
  ('car', 'pickup_locations', 'Teslim alma noktaları', 'textarea', true, '[]'::jsonb, 60),
  ('car', 'deposit_policy', 'Depozito politikası', 'text', true, '[]'::jsonb, 70),
  ('cinema', 'venue', 'Mekân', 'text', true, '[]'::jsonb, 10),
  ('cinema', 'movie_or_program', 'Film / program', 'text', true, '[]'::jsonb, 20),
  ('cinema', 'session_time', 'Seans zamanı', 'text', true, '[]'::jsonb, 30),
  ('cinema', 'seat_type', 'Koltuk tipi', 'text', false, '[]'::jsonb, 40),
  ('cinema', 'ticket_rules', 'Bilet kuralları', 'text', true, '[]'::jsonb, 50),
  ('cruise', 'ship_or_provider', 'Gemi / sağlayıcı', 'text', true, '[]'::jsonb, 10),
  ('cruise', 'route', 'Rota', 'text', true, '[]'::jsonb, 20),
  ('cruise', 'departure_port', 'Kalkış limanı', 'text', true, '[]'::jsonb, 30),
  ('cruise', 'cabin_types', 'Kabin tipleri', 'textarea', false, '[]'::jsonb, 40),
  ('cruise', 'duration', 'Süre', 'text', true, '[]'::jsonb, 50),
  ('cruise', 'board_type', 'Pansiyon tipi', 'text', false, '[]'::jsonb, 60),
  ('event', 'event_type', 'Etkinlik türü', 'select', true, '["Konser", "Festival", "Sergi", "Spor", "Tiyatro", "Workshop", "Seminer"]'::jsonb, 10),
  ('event', 'venue', 'Mekân', 'text', true, '[]'::jsonb, 20),
  ('event', 'start_datetime', 'Başlangıç zamanı', 'text', true, '[]'::jsonb, 30),
  ('event', 'end_datetime', 'Bitiş zamanı', 'text', false, '[]'::jsonb, 40),
  ('event', 'ticket_type', 'Bilet tipi', 'text', true, '[]'::jsonb, 50),
  ('event', 'age_limit', 'Yaş sınırı', 'text', false, '[]'::jsonb, 60),
  ('ferry', 'route_from', 'Kalkış noktası', 'text', true, '[]'::jsonb, 10),
  ('ferry', 'route_to', 'Varış noktası', 'text', true, '[]'::jsonb, 20),
  ('ferry', 'operator', 'Operatör', 'text', false, '[]'::jsonb, 30),
  ('ferry', 'schedule', 'Sefer planı', 'textarea', true, '[]'::jsonb, 40),
  ('ferry', 'vehicle_allowed', 'Araç kabulü', 'boolean', false, '[]'::jsonb, 50),
  ('ferry', 'ticket_rules', 'Bilet kuralları', 'text', true, '[]'::jsonb, 60),
  ('flight', 'airline_or_provider', 'Havayolu / sağlayıcı', 'text', true, '[]'::jsonb, 10),
  ('flight', 'route_from', 'Kalkış noktası', 'text', true, '[]'::jsonb, 20),
  ('flight', 'route_to', 'Varış noktası', 'text', true, '[]'::jsonb, 30),
  ('flight', 'fare_class', 'Bilet sınıfı', 'select', false, '["Ekonomi", "Premium Ekonomi", "Business", "First", "Charter"]'::jsonb, 40),
  ('flight', 'baggage_policy', 'Bagaj politikası', 'text', true, '[]'::jsonb, 50),
  ('flight', 'ticket_rules', 'Bilet kuralları', 'text', true, '[]'::jsonb, 60),
  ('holiday_home', 'property_type', 'Tatil evi türü', 'select', true, '["Villa", "Apart", "Bungalov", "Daire", "Residence"]'::jsonb, 10),
  ('holiday_home', 'bedroom_count', 'Yatak odası sayısı', 'number', true, '[]'::jsonb, 20),
  ('holiday_home', 'bathroom_count', 'Banyo sayısı', 'number', true, '[]'::jsonb, 30),
  ('holiday_home', 'guest_capacity', 'Misafir kapasitesi', 'number', true, '[]'::jsonb, 40),
  ('holiday_home', 'pool_type', 'Havuz tipi', 'select', false, '["Yok", "Özel Havuz", "Ortak Havuz", "Isıtmalı Havuz", "Korunaklı Havuz"]'::jsonb, 50),
  ('holiday_home', 'kitchen', 'Mutfak', 'select', false, '["Yok", "Mini Mutfak", "Tam Donanımlı Mutfak", "Açık Mutfak"]'::jsonb, 60),
  ('holiday_home', 'season_rules', 'Sezon kuralları', 'textarea', false, '[]'::jsonb, 70),
  ('hotel', 'property_type', 'Tesis türü', 'select', true, '["Otel", "Butik Otel", "Apart Otel", "Pansiyon", "Resort", "Tatil Köyü"]'::jsonb, 10),
  ('hotel', 'room_types', 'Oda tipleri', 'textarea', true, '[]'::jsonb, 20),
  ('hotel', 'board_type', 'Pansiyon tipi', 'select', true, '["Oda Kahvaltı", "Yarım Pansiyon", "Tam Pansiyon", "Her Şey Dahil", "Ultra Her Şey Dahil", "Sadece Oda"]'::jsonb, 30),
  ('hotel', 'check_in_time', 'Giriş saati', 'text', true, '[]'::jsonb, 40),
  ('hotel', 'check_out_time', 'Çıkış saati', 'text', true, '[]'::jsonb, 50),
  ('hotel', 'amenities', 'Tesis olanakları', 'textarea', false, '[]'::jsonb, 60),
  ('hotel', 'star_rating', 'Yıldız / sınıf', 'select', false, '["1", "2", "3", "4", "5", "Boutique", "Special Class"]'::jsonb, 70),
  ('pilgrimage', 'package_type', 'Paket türü', 'select', true, '["Hac", "Umre", "Ramazan Umresi", "Kudüs & Umre", "Özel Grup"]'::jsonb, 10),
  ('pilgrimage', 'departure_city', 'Kalkış şehri', 'text', true, '[]'::jsonb, 20),
  ('pilgrimage', 'duration', 'Süre', 'text', true, '[]'::jsonb, 30),
  ('pilgrimage', 'hotel_class', 'Otel sınıfı', 'text', false, '[]'::jsonb, 40),
  ('pilgrimage', 'visa_included', 'Vize dahil', 'boolean', false, '[]'::jsonb, 50),
  ('pilgrimage', 'guidance_included', 'Rehberlik dahil', 'boolean', true, '[]'::jsonb, 60),
  ('restaurant', 'cuisine_type', 'Mutfak türü', 'text', true, '[]'::jsonb, 10),
  ('restaurant', 'venue', 'Mekân', 'text', true, '[]'::jsonb, 20),
  ('restaurant', 'reservation_type', 'Rezervasyon tipi', 'select', true, '["Masa", "Menü", "Etkinlik", "Grup", "Özel Salon"]'::jsonb, 30),
  ('restaurant', 'capacity', 'Kapasite', 'number', false, '[]'::jsonb, 40),
  ('restaurant', 'menu_options', 'Menü seçenekleri', 'textarea', false, '[]'::jsonb, 50),
  ('restaurant', 'service_hours', 'Servis saatleri', 'text', true, '[]'::jsonb, 60),
  ('tour', 'tour_type', 'Tur türü', 'select', true, '["Kültür", "Doğa", "Şehir", "Günübirlik", "Çok Günlü", "Özel Tur"]'::jsonb, 10),
  ('tour', 'tour_subcategory', 'Tur alt kategorisi', 'select', false, '["tour_abroad", "tour_culture", "tour_cruise", "tour_daily", "tour_religious"]'::jsonb, 11),
  ('tour', 'duration', 'Süre', 'text', true, '[]'::jsonb, 20),
  ('tour', 'start_point', 'Başlangıç noktası', 'text', true, '[]'::jsonb, 30),
  ('tour', 'end_point', 'Bitiş noktası', 'text', false, '[]'::jsonb, 40),
  ('tour', 'guide_languages', 'Rehber dilleri', 'text', false, '[]'::jsonb, 50),
  ('tour', 'group_size_min', 'Minimum grup', 'number', false, '[]'::jsonb, 60),
  ('tour', 'group_size_max', 'Maksimum grup', 'number', false, '[]'::jsonb, 70),
  ('transfer', 'transfer_type', 'Transfer türü', 'select', true, '["Havalimanı", "Otel", "Şehir İçi", "Şehirler Arası", "Vip", "Grup"]'::jsonb, 10),
  ('transfer', 'pickup_location', 'Alış noktası', 'text', true, '[]'::jsonb, 20),
  ('transfer', 'dropoff_location', 'Bırakış noktası', 'text', true, '[]'::jsonb, 30),
  ('transfer', 'vehicle_type', 'Araç tipi', 'text', true, '[]'::jsonb, 40),
  ('transfer', 'capacity', 'Kapasite', 'number', true, '[]'::jsonb, 50),
  ('transfer', 'waiting_policy', 'Bekleme politikası', 'text', false, '[]'::jsonb, 60),
  ('visa', 'destination_country', 'Hedef ülke', 'text', true, '[]'::jsonb, 10),
  ('visa', 'visa_type', 'Vize türü', 'select', true, '["Turistik", "Ticari", "Öğrenci", "Aile Ziyareti", "Transit", "Çalışma"]'::jsonb, 20),
  ('visa', 'processing_time', 'İşlem süresi', 'text', true, '[]'::jsonb, 30),
  ('visa', 'required_documents', 'Gerekli belgeler', 'textarea', true, '[]'::jsonb, 40),
  ('visa', 'appointment_required', 'Randevu gerekli', 'boolean', false, '[]'::jsonb, 50),
  ('yacht', 'yacht_type', 'Yat / tekne türü', 'select', true, '["Gulet", "Motoryat", "Yelkenli", "Katamaran", "Tekne"]'::jsonb, 10),
  ('yacht', 'capacity', 'Kapasite', 'number', true, '[]'::jsonb, 20),
  ('yacht', 'cabin_count', 'Kabin sayısı', 'number', false, '[]'::jsonb, 30),
  ('yacht', 'departure_port', 'Kalkış limanı', 'text', true, '[]'::jsonb, 40),
  ('yacht', 'route', 'Rota', 'text', true, '[]'::jsonb, 50),
  ('yacht', 'captain_included', 'Kaptan dahil', 'boolean', true, '[]'::jsonb, 60),
  ('yacht', 'fuel_policy', 'Yakıt politikası', 'text', false, '[]'::jsonb, 70)
) AS v(category_code, field_key, label, field_type, required, options, sort_order)
JOIN agency.categories target
  ON target.code = v.category_code
 AND target.parent_id IS NULL
 AND target.active
ON CONFLICT (category_id, field_key) DO NOTHING;
