const {test,expect}=require('@playwright/test');const {execFileSync}=require('node:child_process');const {randomUUID,createHmac}=require('node:crypto');
const tenant=randomUUID(),other=randomUUID(),admin=randomUUID(),customer=randomUUID(),password='setup-fixture-password';
function sql(input){return execFileSync('C:/laragon/bin/postgresql/postgresql/bin/psql.exe',['-X','-w','-U','postgres','-d','nexus_agency','-v','ON_ERROR_STOP=1','-At'],{input,encoding:'utf8'}).trim();}
test.beforeAll(()=>sql(`INSERT INTO agency.tenants(id,legal_name,brand_name,slug) VALUES('${tenant}','Setup fixture','Setup','${tenant}'),('${other}','Other fixture','Other','${other}'); INSERT INTO agency.users(id,tenant_id,email,display_name,membership_type,password_hash) VALUES('${admin}','${tenant}','admin@setup.example.test','Setup admin','admin',crypt('${password}',gen_salt('bf',4))),('${customer}','${tenant}','customer@setup.example.test','Customer','customer',crypt('${password}',gen_salt('bf',4))); INSERT INTO agency.customer_verification(user_id,tenant_id,email_verified_at,phone) VALUES('${customer}','${tenant}',now(),'+905551234567');`));
test.afterAll(()=>sql(`DELETE FROM agency.tenants WHERE id IN ('${tenant}','${other}');`));
async function login(page){await page.goto('/login');await page.locator('[name=email]').fill('admin@setup.example.test');await page.locator('[name=tenant_slug]').fill(tenant);await page.locator('[name=password]').fill(password);await page.locator('form button[type=submit]').click();await page.waitForURL('**/admin');await page.goto('/admin/membership-setup');}
async function post(page,action,fields){return page.request.post('/admin/membership-setup/'+action,{headers:{origin:new URL(page.url()).origin},form:{csrf:await page.locator('meta[name=csrf-token]').getAttribute('content'),password,...fields}});}
test('setup checklist fits mobile, scoped state and missing-provider test',async({page})=>{await page.setViewportSize({width:360,height:844});await login(page);await expect(page.locator('#setup-checklist')).toContainText('E-posta gönderimi');await expect(page.locator('#setup-checklist')).toContainText('Eksik');expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);let r=await post(page,'test',{channel:'email',target:'admin@setup.example.test'});expect(r.status()).toBe(200);expect((await r.json()).status).toBe('provider_unavailable');r=await post(page,'webhook',{password:'incorrect',app_secret:'fixture-app-secret-value',verify_token:'fixture-verify-token-value'});expect(r.status()).toBe(403);r=await page.request.get('/api/webhooks/membership-whatsapp/'+other+'?hub.mode=subscribe&hub.verify_token=fixture-verify-token-value&hub.challenge=123');expect(r.status()).toBe(503);});
test('panel saves sealed webhook keys; callback validates signatures and delivery scope',async({page})=>{await login(page);const appSecret='fixture-app-secret-value',verify='fixture-verify-token-value';let r=await post(page,'webhook',{app_secret:appSecret,verify_token:verify});expect(r.status()).toBe(200);expect((await r.json()).status).toBe('saved');expect(sql(`SELECT value#>>'{}' FROM agency.settings WHERE tenant_id='${tenant}' AND key='membership_whatsapp_app_secret_sealed';`)).not.toContain(appSecret);r=await page.request.get('/api/webhooks/membership-whatsapp/'+tenant+'?hub.mode=subscribe&hub.verify_token='+verify+'&hub.challenge=12345');expect(r.status()).toBe(200);expect(await r.text()).toBe('12345');r=await page.request.get('/api/webhooks/membership-whatsapp/'+tenant+'?hub.mode=subscribe&hub.verify_token=wrong&hub.challenge=12345');expect(r.status()).toBe(403);
 const challenge=randomUUID(),job=randomUUID();sql(`INSERT INTO agency.integrations(tenant_id,provider,kind,active,credentials) VALUES('${tenant}','sms_whatsapp','notification',true,'{"whatsapp_phone_id":"123456789","whatsapp_token_sealed":"fixture"}'); INSERT INTO agency.customer_auth_challenges(id,tenant_id,user_id,purpose,channel,code_hash,expires_at) VALUES('${challenge}','${tenant}','${customer}','phone','whatsapp','fixture',now()+interval '10 minutes'); INSERT INTO agency.customer_phone_outbox(id,tenant_id,user_id,challenge_id,phone,code,status,provider_message_id,delivery_status) VALUES('${job}','${tenant}','${customer}','${challenge}','+905551234567','','sent','fixture-browser-message','accepted');`);
 const body=JSON.stringify({object:'whatsapp_business_account',entry:[{changes:[{value:{metadata:{phone_number_id:'123456789'},statuses:[{id:'fixture-browser-message',status:'delivered'}]}}]}]});const signature='sha256='+createHmac('sha256',appSecret).update(body).digest('hex');r=await page.request.post('/api/webhooks/membership-whatsapp/'+tenant,{data:body,headers:{'content-type':'application/json','x-hub-signature-256':'sha256=bad'}});expect(r.status()).toBe(401);r=await page.request.post('/api/webhooks/membership-whatsapp/'+tenant,{data:body,headers:{'content-type':'application/json','x-hub-signature-256':signature}});expect(r.status()).toBe(200);expect(sql(`SELECT delivery_status FROM agency.customer_phone_outbox WHERE id='${job}';`)).toBe('delivered');
 r=await page.request.get('/admin/membership-setup/data');const data=await r.json();expect(data.webhook).toBe(true);expect(JSON.stringify(data)).not.toContain(appSecret);expect(JSON.stringify(data)).not.toContain('code_hash');
});
test('SMTP panel seals credentials and queues restricted test email',async({page})=>{await login(page);let r=await post(page,'smtp',{host:'127.0.0.1',username:'fixture',smtp_password:'smtp-fixture-private',from:'sender@setup.example.test',port:'587'});expect(r.status()).toBe(200);expect((await r.json()).status).toBe('saved');expect(sql(`SELECT value#>>'{}' FROM agency.settings WHERE tenant_id='${tenant}' AND key='smtp_password_sealed';`)).not.toContain('smtp-fixture-private');r=await post(page,'test',{channel:'email',target:'unrelated@example.test'});expect((await r.json()).status).toBe('own_email_required');r=await post(page,'test',{channel:'email',target:'admin@setup.example.test'});expect((await r.json()).status).toBe('queued');sql(`UPDATE agency.notifications SET status='failed' WHERE tenant_id='${tenant}' AND template='membership.connection.test';`);r=await post(page,'test',{channel:'email',target:'admin@setup.example.test'});expect((await r.json()).status).toBe('rate_limited');await page.locator('#setup-refresh').click();await expect(page.locator('#setup-tests')).toContainText('Başarısız');});

test('member overview shows verification summary and next step in selected language',async({page})=>{await page.setViewportSize({width:360,height:844});await page.goto('/uye-girisi?tenant='+tenant);const csrf=await page.locator('meta[name=csrf-token]').getAttribute('content');const r=await page.request.post('/api/public/membership/login?tenant='+tenant,{form:{csrf,email:'customer@setup.example.test',password}});expect((await r.json()).status).toBe('authenticated');await page.goto('/hesap?tenant='+tenant+'&lang=en');await expect(page.locator('[data-verification-summary]')).toContainText('Membership verification status');expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);await page.locator('[data-verification-summary] [data-open=profile]').click();await expect(page.locator('.cv-progress')).toBeVisible();await expect(page.locator('[data-pane=profile] .cv-card')).toContainText('Next step: Verify the WhatsApp code');});
