const {test,expect}=require('@playwright/test');
const {execFileSync}=require('node:child_process');const {randomUUID}=require('node:crypto');
const tenant=randomUUID(),admin=randomUUID(),customer=randomUUID(),password='security-fixture-password';
function sql(text){return execFileSync('C:/laragon/bin/postgresql/postgresql/bin/psql.exe',['-X','-w','-U','postgres','-d','nexus_agency','-v','ON_ERROR_STOP=1','-At'],{input:text,encoding:'utf8'}).trim();}
test.beforeAll(()=>sql(`INSERT INTO agency.tenants(id,legal_name,brand_name,slug) VALUES('${tenant}','E2E security','Security test','${tenant}'); INSERT INTO agency.settings(tenant_id,key,value) VALUES('${tenant}','contract_membership','\"Test membership agreement document\"'),('${tenant}','contract_privacy_policy','\"Test privacy notice document\"'); INSERT INTO agency.users(id,tenant_id,email,display_name,membership_type,password_hash) VALUES('${admin}','${tenant}','admin@security.example.test','Security admin','admin',crypt('${password}',gen_salt('bf',4))),('${customer}','${tenant}','customer@security.example.test','Security customer','customer',crypt('${password}',gen_salt('bf',4))); INSERT INTO agency.customer_verification(user_id,tenant_id,email_verified_at,phone) VALUES('${customer}','${tenant}',now(),'+905551234567');`));
test.afterAll(()=>sql(`DELETE FROM agency.tenants WHERE id='${tenant}'::uuid;`));
test('membership supports six languages and keeps consent tenant scope',async({page})=>{for(const lang of ['en','de','ru','fr','zh','tr']){await page.goto('/uye-ol?tenant='+tenant+'&lang='+lang);await expect(page.locator('.member-language')).toHaveValue(lang);await expect(page.locator('h2')).toHaveText({tr:'Üye olun',en:'Create an account',de:'Konto erstellen',ru:'Создать аккаунт',fr:'Créer un compte',zh:'创建账户'}[lang]);await expect(page.locator('a[href*="uyelik-kosullari"]')).toHaveAttribute('href','/uyelik-kosullari?tenant='+tenant);}});
test('customer can list sessions; phone requests require signed session',async({page})=>{await page.goto('/uye-girisi?tenant='+tenant);let csrf=await page.locator('meta[name=csrf-token]').getAttribute('content');let r=await page.request.post('/api/public/membership/request?tenant='+tenant,{form:{csrf,purpose:'phone'}});expect(r.status()).toBe(401);r=await page.request.post('/api/public/membership/login?tenant='+tenant,{form:{csrf,email:'customer@security.example.test',password}});expect(r.status()).toBe(200);expect((await r.json()).status).toBe('authenticated');await page.goto('/uye-girisi?tenant='+tenant);csrf=await page.locator('meta[name=csrf-token]').getAttribute('content');r=await page.request.post('/api/public/membership/sessions?tenant='+tenant,{form:{csrf}});expect(r.status()).toBe(200);const rows=await r.json();expect(rows.some(x=>x.current)).toBe(true);expect(rows.every(x=>x.id.length===64)).toBe(true);r=await page.request.post('/api/public/membership/request?tenant='+tenant,{form:{csrf,purpose:'phone',email:'admin@security.example.test'}});expect((await r.json()).status).toBe('provider_unavailable');});
test('admin MFA enrollment requires password and renders recovery codes',async({page})=>{await page.goto('/login');await page.locator('[name=email]').fill('admin@security.example.test');await page.locator('[name=tenant_slug]').fill(tenant);await page.locator('[name=password]').fill(password);await page.locator('form button[type=submit]').click();await page.waitForURL('**/admin');await page.goto('/admin/security');expect(await page.locator('#admin-mfa-form').count()).toBe(1);await page.locator('[name=password]').fill(password);const response=page.waitForResponse(r=>r.url().includes('/admin/security/begin'));await page.locator('[data-action=begin]').click();const enrollment=await response;expect(enrollment.status()).toBe(200);const setup=await enrollment.json();expect(setup.status).toBe('pending');await expect(page.locator('[data-setup]')).toContainText('Tek kullanımlık kurtarma kodları');expect(sql(`SELECT count(*) FROM agency.admin_mfa WHERE user_id='${admin}' AND NOT enabled;`)).toBe('1');await page.locator('[name=code]').fill(setup.backupCodes[0]);const enableResponse=page.waitForResponse(r=>r.url().includes('/admin/security/enable'));await page.locator('[data-action=enable]').click();expect((await (await enableResponse).json()).status).toBe('enabled');
await page.context().clearCookies();await page.goto('/login');let r=await page.request.post('/login',{form:{email:'admin@security.example.test',tenant_slug:tenant,password},maxRedirects:0});expect(r.status()).toBe(401);
r=await page.request.post('/login',{form:{email:'admin@security.example.test',tenant_slug:tenant,password,mfa_code:setup.backupCodes[1]},maxRedirects:0});expect(r.status()).toBe(303);
await page.context().clearCookies();await page.goto('/login');r=await page.request.post('/login',{form:{email:'admin@security.example.test',tenant_slug:tenant,password,mfa_code:setup.backupCodes[1]},maxRedirects:0});expect(r.status()).toBe(401);
});

test('real registration verifies email before granting customer access',async({page})=>{
 const email='signup@security.example.test';await page.goto('/uye-ol?tenant='+tenant);const csrf=await page.locator('meta[name=csrf-token]').getAttribute('content');
 let r=await page.request.post('/api/public/membership/register?tenant='+tenant,{form:{csrf,name:'New Test Customer',email,phone:'+905551234567',password,terms:'on',lang:'en'}});expect(r.status()).toBe(200);expect((await r.json()).status).toBe('accepted');
 const code=sql(`SELECT substring(payload->>'html' FROM '<strong>([0-9]+)</strong>') FROM agency.notifications WHERE tenant_id='${tenant}' AND template='customer.auth.email' AND payload->>'to'='${email}'; UPDATE agency.notifications SET status='failed' WHERE tenant_id='${tenant}' AND template='customer.auth.email';`).split('\n')[0].trim();expect(code.length).toBe(8);
 r=await page.request.post('/api/public/membership/login?tenant='+tenant,{form:{csrf,email,password}});expect((await r.json()).status).toBe('email_pending');
 r=await page.request.post('/api/public/membership/confirm?tenant='+tenant,{form:{csrf,email,purpose:'email',code}});expect((await r.json()).status).toBe('verified');
 r=await page.request.post('/api/public/membership/login?tenant='+tenant,{form:{csrf,email,password}});expect((await r.json()).status).toBe('authenticated');
 r=await page.request.get('/api/public/account');expect(r.status()).toBe(200);expect((await r.json()).email).toBe(email);
});

test('WhatsApp worker fails safely without valid credentials',async({page})=>{
 test.setTimeout(60000);sql(`INSERT INTO agency.integrations(tenant_id,provider,kind,active,credentials) VALUES('${tenant}','sms_whatsapp','notification',true,'{"whatsapp_phone_id":"123456789","whatsapp_token_sealed":"invalid-local-test"}'); INSERT INTO agency.settings(tenant_id,key,value) VALUES('${tenant}','whatsapp_auth_template','"auth_test"'),('${tenant}','whatsapp_auth_language','"tr"'),('${tenant}','whatsapp_api_version','"v25.0"');`);
 await page.goto('/uye-girisi?tenant='+tenant);let csrf=await page.locator('meta[name=csrf-token]').getAttribute('content');let r=await page.request.post('/api/public/membership/login?tenant='+tenant,{form:{csrf,email:'customer@security.example.test',password}});expect((await r.json()).status).toBe('authenticated');await page.goto('/uye-girisi?tenant='+tenant);csrf=await page.locator('meta[name=csrf-token]').getAttribute('content');
 r=await page.request.post('/api/public/membership/request?tenant='+tenant,{form:{csrf,purpose:'phone'}});expect((await r.json()).status).toBe('accepted');
 await expect.poll(()=>sql(`SELECT status FROM agency.customer_phone_outbox WHERE tenant_id='${tenant}';`),{timeout:45000,intervals:[1000,2000,5000]}).toBe('failed');
 expect(sql(`SELECT length(code) FROM agency.customer_phone_outbox WHERE tenant_id='${tenant}';`)).toBe('0');expect(sql(`SELECT phone_verified_at IS NULL FROM agency.customer_verification WHERE user_id='${customer}';`)).toBe('t');
 await page.setViewportSize({width:360,height:844});await page.goto('/hesap?tenant='+tenant+'&lang=en#profile');await expect(page.locator('.cv-card h3')).toHaveText('Verification and security');await expect(page.locator('[data-contact]')).toBeVisible();await expect(page.locator('[data-sessions]')).toContainText('This session');expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});

test('manual review page requires renewed administrator authentication',async({page})=>{
 const reviewer=randomUUID();sql(`INSERT INTO agency.users(id,tenant_id,email,display_name,membership_type,password_hash) VALUES('${reviewer}','${tenant}','reviewer@security.example.test','Reviewer','admin',crypt('${password}',gen_salt('bf',4))); SELECT agency.submit_customer_identity('${tenant}','${customer}','10000000146','1990-01-01'); UPDATE agency.notifications SET status='failed' WHERE tenant_id='${tenant}' AND status='queued';`);
 await page.goto('/login');await page.locator('[name=email]').fill('reviewer@security.example.test');await page.locator('[name=tenant_slug]').fill(tenant);await page.locator('[name=password]').fill(password);await page.locator('form button[type=submit]').click();await page.waitForURL('**/admin');await page.goto('/admin/customer-verification');await expect(page.locator('#customer-verification-admin')).toContainText('Bekleyen başvuru: 1');
 const csrf=await page.locator('meta[name=csrf-token]').getAttribute('content');const form={csrf,user_id:customer,decision:'manual_approved',reason:'Reviewed synthetic test identity record',password:'incorrect'};const headers={origin:new URL(page.url()).origin};let r=await page.request.post('/admin/customer-verification/review',{form,headers});expect(r.status()).toBe(403);
 form.password=password;r=await page.request.post('/admin/customer-verification/review',{form,headers});expect(r.status()).toBe(200);expect((await r.json()).status).toBe('manual_approved');expect(sql(`SELECT identity_status FROM agency.customer_verification WHERE user_id='${customer}';`)).toBe('manual_approved');
});
