const {test,expect}=require('@playwright/test');const {execFileSync}=require('node:child_process');const {randomUUID}=require('node:crypto');
const tenant=randomUUID(),admin=randomUUID(),other=randomUUID();const codes=['hotel','holiday_home','yacht','tour','activity','flight','car','cruise','pilgrimage','visa','ferry','transfer','beach','cinema','event','restaurant','bus'];const ids=codes.map(()=>randomUUID());
function sql(input){return execFileSync('C:/laragon/bin/postgresql/postgresql/bin/psql.exe',['-X','-w','-U','postgres','-d','nexus_agency','-v','ON_ERROR_STOP=1','-At'],{input,encoding:'utf8'}).trim();}
test.beforeAll(()=>{sql(`INSERT INTO agency.tenants(id,legal_name,brand_name,slug) VALUES('${tenant}','SEO fixture','SEO fixture','${tenant}'),('${other}','SEO other','SEO other','${other}'); INSERT INTO agency.users(id,tenant_id,email,display_name,membership_type,password_hash) VALUES('${admin}','${tenant}','admin@seo.example.test','SEO admin','admin',crypt('seo-fixture-password',gen_salt('bf',4)));`);sql(`INSERT INTO agency.pages(tenant_id,slug,template,status,seo,published_at) VALUES('${tenant}','seo-fixture-guide','standard','published','{"title":"SEO guide","description":"Unique guide description"}',now());`);codes.forEach((c,i)=>sql(`INSERT INTO agency.listings(id,tenant_id,code,category,title,description,locality,currency,price_minor,source,owner_info,cancellation_policy,images,metadata,status) VALUES('${ids[i]}','${tenant}','seo-${i}','${c}','SEO ${c}','Gerçek ilan açıklaması ve özel hizmet bilgileri.','Göcek','TRY',4200000,'manual','{"name":"SEO fixture"}','{"policy":"14 gün"}','["/static/favicon.svg"]',(SELECT coalesce(jsonb_object_agg(f.field_key,'fixture'),'{}'::jsonb) FROM agency.categories c JOIN agency.category_fields f ON f.category_id=c.id WHERE c.tenant_id='${tenant}' AND c.code='${c}' AND f.required),'published');`));});
test.afterAll(()=>sql(`DELETE FROM agency.tenants WHERE id IN ('${tenant}','${other}');`));
async function scope(context){await context.addCookies([{name:'nexus_public_tenant',value:tenant,url:'http://127.0.0.1:8082'}]);}
async function post(page,action,fields){return page.request.post('/admin/seo/'+action,{headers:{origin:new URL(page.url()).origin},form:{csrf:await page.locator('meta[name=csrf-token]').getAttribute('content'),...fields}});}
test('all 17 new categories have SEO, stable redirects, private/preview excluded',async({page,context})=>{await scope(context);expect(sql(`SELECT count(*) FROM agency.listing_seo WHERE tenant_id='${tenant}';`)).toBe('17');const content=await page.request.get('/sitemap-content.xml');expect(await content.text()).toContain('/seo-fixture-guide');let cms=await page.request.get('/seo-fixture-guide');expect(cms.status()).toBe(200);expect(await cms.text()).toContain('Unique guide description');const map=await page.request.get('/sitemap-listings.xml');expect(map.status()).toBe(200);expect((await map.text()).match(/<url>/g)).toHaveLength(17);for(const id of ids){let r=await page.request.get('/urunler/'+id,{maxRedirects:0});expect(r.status()).toBe(301);const url=r.headers().location;r=await page.request.get(url);expect(r.status()).toBe(200);expect(r.headers()['x-robots-tag']).toContain('index,follow');const body=await r.text();expect(body).toContain('rel="canonical"');expect(body).toContain('application/ld+json');expect(body).not.toContain('InStock');expect(body).toContain('Gerçek ilan açıklaması');}
 const id=ids[2],slug=sql(`SELECT stable_slug FROM agency.listing_seo WHERE listing_id='${id}';`);sql(`UPDATE agency.listings SET title='Yeni Yat Başlığı' WHERE id='${id}';`);expect(sql(`SELECT stable_slug FROM agency.listing_seo WHERE listing_id='${id}';`)).toBe(slug);let r=await page.request.get('/yat/yeni-yat-basligi',{maxRedirects:0});expect(r.status()).toBe(301);expect(r.headers().location).toContain(slug);r=await page.request.get('/yat/'+slug+'?preview=booking');expect(r.headers()['x-robots-tag']).toContain('noindex');r=await page.request.get('/login');expect(r.headers()['x-robots-tag']).toContain('noindex');r=await page.request.get('/yat/'+slug+'?tenant='+other);expect(r.status()).toBe(404);
});
test('SEO panel scoped overrides, translation SSR and sitemap, mobile',async({page,context})=>{await scope(context);await page.setViewportSize({width:360,height:844});await page.goto('/login');await page.locator('[name=email]').fill('admin@seo.example.test');await page.locator('[name=tenant_slug]').fill(tenant);await page.locator('[name=password]').fill('seo-fixture-password');await page.locator('form button[type=submit]').click();await page.waitForURL('**/admin');await page.goto('/admin/seo');await expect(page.locator('#seo-documents article')).toHaveCount(17);expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
 let r=await post(page,'save',{id:ids[1],title:'Özel SEO başlığı',description:'Özel SEO açıklaması'});expect((await r.json()).saved).toBe(true);r=await post(page,'translations',{id:ids[1],lang:'en',title:'Gocek holiday home',description:'A private holiday home in Gocek.'});expect((await r.json()).saved).toBe(true);const slug=sql(`SELECT stable_slug FROM agency.listing_seo WHERE listing_id='${ids[1]}';`);r=await page.request.get('/tatil-evi/'+slug+'?lang=en');expect(r.status()).toBe(200);const html=await r.text();expect(html).toContain('<html lang="en">');expect(html).toMatch(/<h1[^>]*>Gocek holiday home<\/h1>/);expect(html).toContain('hreflang="en"');expect(html).toContain('A private holiday home in Gocek.');r=await page.request.get('/tatil-evi/'+slug+'?lang=de');expect(r.headers()['x-robots-tag']).toContain('noindex');expect(await r.text()).toContain('<html lang="tr">');r=await page.request.get('/sitemap-listings.xml');expect(await r.text()).toContain('/en/holiday-home/');r=await post(page,'save',{id:ids[1],noindex:'on'});expect((await r.json()).saved).toBe(true);r=await page.request.get('/sitemap-listings.xml');expect(await r.text()).not.toContain(slug);await page.goto('/tatil-evi/'+slug+'?lang=en');await expect(page.locator('main h1')).toHaveText('Gocek holiday home');await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href',new RegExp('/en/holiday-home/'));await expect(page.locator('meta[name=robots]')).toHaveAttribute('content','noindex,follow');
 r=await post(page,'config',{seo_public_origin:'https://seo.example.test',seo_home_title:'SEO test site',seo_home_description:'SEO test description'});expect((await r.json()).saved).toBe(true);r=await page.request.get('/');expect(await r.text()).toContain('<title>SEO test site</title>');r=await page.request.get('/sitemap-index.xml');expect(await r.text()).toContain('https://seo.example.test');
});
test('six independent SEO profiles, localized URLs, aliases and protected paths',async({page,context})=>{
 await scope(context);await page.goto('/login');await page.locator('[name=email]').fill('admin@seo.example.test');await page.locator('[name=tenant_slug]').fill(tenant);await page.locator('[name=password]').fill('seo-fixture-password');await page.locator('form button[type=submit]').click();await page.waitForURL('**/admin');await page.goto('/admin/seo');
 sql(`DELETE FROM agency.settings WHERE tenant_id='${tenant}' AND key='seo_public_origin';`);const profiles=await (await page.request.get('/admin/seo/locales')).json();const key='listing:'+ids[2];expect(profiles.filter(x=>x.resource_key===key)).toHaveLength(6);
 const variants=[['tr','/yat/seo-yacht','Türkçe SEO','Türkçe açıklama','yat, göcek'],['en','/en/yacht/gocek-gulet','English SEO','English description','yacht, charter'],['de','/de/yacht/gocek-gulet','Deutscher SEO Titel','Deutsche Beschreibung','yacht, mieten'],['ru','/ru/yahta/gocek-gulet','Русский SEO','Русское описание','яхта, аренда'],['fr','/fr/yacht/gocek-gulet','SEO français','Description française & détails','yacht, location'],['zh','/zh/youting/gocek-gulet','中文SEO','中文说明','游艇, 租赁']];
 for(const [lang,path,title,description,keywords] of variants){const r=await post(page,'locales',{resource_key:key,lang,path,title,description,keywords,og_title:title+' social',og_description:description+' social',content_title:title+' listing',content_description:description+' content'});expect((await r.json()).saved).toBe(true);}
 for(const [lang,path,title,description,keywords] of variants){const r=await page.request.get(path);expect(r.status()).toBe(200);const html=await r.text();expect(html).toContain('<html lang="'+lang+'">');expect(html).toContain('<title>'+title+'</title>');expect(html).toContain('name="keywords" content="'+keywords+'"');expect(html).toContain('href="http://127.0.0.1:8082'+path+'"');expect(html).toContain('hreflang="fr"');expect(html).not.toContain('?lang=');expect(html).toContain(title+' social');}
 let r=await page.request.get('/yat/seo-yacht?lang=en',{maxRedirects:0});expect(r.status()).toBe(301);expect(r.headers().location).toMatch(new RegExp('/en/yacht/gocek-gulet$'));const en=profiles.find(x=>x.resource_key===key&&x.language_code==='en');r=await page.request.get(en.path,{maxRedirects:0});expect(r.status()).toBe(301);
 r=await post(page,'locales',{resource_key:key,lang:'en',path:'/en/yacht/gocek-new',title:'New English SEO',description:'New description'});expect((await r.json()).saved).toBe(true);r=await page.request.get('/en/yacht/gocek-gulet',{maxRedirects:0});expect(r.status()).toBe(301);expect(r.headers().location).toMatch(new RegExp('/en/yacht/gocek-new$'));
 r=await post(page,'locales',{resource_key:'listing:'+ids[0],lang:'en',path:'/en/yacht/gocek-new',title:'Collision',description:'Collision'});expect((await r.json()).saved).toBe(false);r=await post(page,'locales',{resource_key:key,lang:'tr',path:'/admin',title:'Bad',description:'Bad'});expect(r.status()).toBe(422);r=await post(page,'locales',{resource_key:'listing:'+randomUUID(),lang:'en',path:'/en/not-mine',title:'Bad',description:'Bad'});expect(r.status()).toBe(422);
 r=await page.request.get('/sitemap-listings.xml');const xml=await r.text();expect(xml).toContain('/en/yacht/gocek-new');expect(xml).not.toContain('/en/yacht/gocek-gulet</loc>');expect(xml).toContain('/zh/youting/gocek-gulet');
 await page.goto('/fr/yacht/gocek-gulet');await expect(page.locator('meta[name=keywords]')).toHaveAttribute('content','yacht, location');await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href','http://127.0.0.1:8082/fr/yacht/gocek-gulet');await page.evaluate(()=>document.dispatchEvent(new CustomEvent('nexus:lang',{detail:{lang:'de'}})));await page.waitForURL('**/de/yacht/gocek-gulet');
});
test('home category and CMS pages have independent language SEO',async({page,context})=>{await scope(context);await page.goto('/login');await page.locator('[name=email]').fill('admin@seo.example.test');await page.locator('[name=tenant_slug]').fill(tenant);await page.locator('[name=password]').fill('seo-fixture-password');await page.locator('form button[type=submit]').click();await page.waitForURL('**/admin');await page.goto('/admin/seo');for(const [key,path] of [['page:/','/en/'],['page:/yat','/en/yacht'],['page:/seo-fixture-guide','/en/travel-guide']]){const r=await post(page,'locales',{resource_key:key,lang:'en',path,title:'English '+key,description:'English page description',keywords:'travel, holiday'});expect((await r.json()).saved).toBe(true);const response=await page.request.get(path);expect(response.status()).toBe(200);const html=await response.text();expect(html).toContain('<title>English '+key+'</title>');expect(response.headers()['x-robots-tag']).toContain('index,follow');}
 const r=await page.request.get('/sitemap-categories.xml');expect(await r.text()).toContain('/en/yacht');await page.goto('/en/yacht');await expect(page.locator('link[hreflang=en]')).toHaveAttribute('href','http://127.0.0.1:8082/en/yacht');expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});
test('public sitemap partitions resolve and UTF-8 stays valid',async({request})=>{for(const p of ['/','/robots.txt','/sitemap.xml','/sitemap-index.xml','/sitemap-categories.xml','/sitemap-content.xml','/sitemap-listings.xml']){const r=await request.get(p);expect(r.status()).toBe(200);const bytes=await r.body();expect(()=>new TextDecoder('utf-8',{fatal:true}).decode(bytes)).not.toThrow();}});

test('real holiday-home mobile gallery retains controls and server indexing directives',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/tatil-evi/bodrum-yalikavak-panoramik-deniz-manzarali-luks-balayi-villasi?preview=booking');await expect(page.locator('.detail-gallery img').first()).toBeVisible();await expect(page.locator('.detail-gallery')).toHaveCount(1);await expect(page.locator('.gallery-showall')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);await expect(page.locator('meta[name=robots]')).toHaveAttribute('content','noindex,follow');await page.locator('.gallery-showall').click();await expect(page.locator('.chisfis-lightbox')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.chisfis-lightbox')).toHaveCount(0);});
