BEGIN;
DO $$ DECLARE t uuid:=gen_random_uuid(); other uuid:=gen_random_uuid(); u uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); c text; result text; j uuid; sid text; i integer; BEGIN
INSERT INTO agency.tenants(id,legal_name,brand_name,slug) VALUES(t,'Security test','Test',t::text),(other,'Other','Other',other::text);
INSERT INTO agency.users(id,tenant_id,email,display_name,membership_type,password_hash) VALUES(u,t,'old@example.test','Test','customer',crypt('long-test-password',gen_salt('bf',4))),(a,t,'admin@example.test','Admin','admin',crypt('long-test-password',gen_salt('bf',4)));
INSERT INTO agency.customer_verification(user_id,tenant_id,phone,email_verified_at) VALUES(u,t,'+905551234567',now());
result:=agency.customer_contact_request(t,u,'email','new@example.test','wrong'); IF result<>'invalid_password' THEN RAISE EXCEPTION 'Password bypass'; END IF;
result:=agency.customer_contact_request(other,u,'email','new@example.test','long-test-password'); IF result<>'invalid_password' THEN RAISE EXCEPTION 'Cross tenant contact'; END IF;
result:=agency.customer_contact_request(t,u,'email','new@example.test','long-test-password'); IF result<>'accepted' THEN RAISE EXCEPTION 'Email change rejected'; END IF;
IF (SELECT email FROM agency.users WHERE id=u)<>'old@example.test' THEN RAISE EXCEPTION 'Email changed before verification'; END IF;
PERFORM agency.customer_localize_email_queue(t,'old@example.test','de');
IF NOT EXISTS(SELECT 1 FROM agency.notifications WHERE user_id=u AND payload->>'subject'='Ihr Bestätigungscode') THEN RAISE EXCEPTION 'Localized email missing'; END IF;
SELECT substring(payload->>'html' FROM '<strong>([0-9]+)</strong>') INTO c FROM agency.notifications WHERE user_id=u AND template='customer.auth.email_change';
result:=agency.customer_contact_confirm(t,u,'email','incorrect'); IF result<>'invalid_code' THEN RAISE EXCEPTION 'Bad code'; END IF;
result:=agency.customer_contact_confirm(t,u,'email',c); IF result<>'verified' OR (SELECT email FROM agency.users WHERE id=u)<>'new@example.test' THEN RAISE EXCEPTION 'Email confirmation failed'; END IF;
IF agency.customer_contact_confirm(t,u,'email',c)<>'invalid_code' THEN RAISE EXCEPTION 'Replayed change'; END IF;
UPDATE agency.customer_auth_challenges SET created_at=now()-interval '2 minutes' WHERE user_id=u;
IF agency.customer_auth_request(t,'new@example.test','phone','whatsapp')<>'provider_unavailable' THEN RAISE EXCEPTION 'Missing provider accepted'; END IF;
INSERT INTO agency.integrations(tenant_id,provider,kind,credentials,active) VALUES(t,'sms_whatsapp','notification','{"whatsapp_phone_id":"123456789","whatsapp_token_sealed":"fake-sealed-test"}',true);
INSERT INTO agency.settings(tenant_id,key,value) VALUES(t,'whatsapp_auth_template','"auth_test"'),(t,'whatsapp_auth_language','"tr"'),(t,'whatsapp_api_version','"v25.0"');
result:=agency.customer_contact_request(t,u,'phone','+905552222222','long-test-password'); IF result<>'accepted' THEN RAISE EXCEPTION 'Phone request rejected: %',result; END IF;
IF (SELECT phone FROM agency.customer_verification WHERE user_id=u)<>'+905551234567' THEN RAISE EXCEPTION 'Phone changed before code'; END IF;
SELECT code,id INTO c,j FROM agency.customer_phone_outbox WHERE user_id=u;
IF (SELECT count(*) FROM agency.customer_phone_claim() WHERE job_id=j::text)<>1 THEN RAISE EXCEPTION 'Job not claimed'; END IF;
IF (SELECT count(*) FROM agency.customer_phone_claim() WHERE job_id=j::text)<>0 THEN RAISE EXCEPTION 'Job claimed twice'; END IF;
PERFORM agency.customer_phone_finish(j,'retry'); IF (SELECT status FROM agency.customer_phone_outbox WHERE id=j)<>'queued' THEN RAISE EXCEPTION 'No retry'; END IF;
result:=agency.customer_contact_confirm(t,u,'phone',c); IF result<>'verified' THEN RAISE EXCEPTION 'Phone confirmation failed'; END IF;
PERFORM agency.customer_phone_claim(); IF (SELECT code FROM agency.customer_phone_outbox WHERE id=j)<>'' THEN RAISE EXCEPTION 'Consumed code retained'; END IF;
INSERT INTO auth.sessions(token_digest,user_id,expires_at) VALUES(encode(digest('current','sha256'),'hex'),u,now()+interval '1 hour'),(encode(digest('other','sha256'),'hex'),u,now()+interval '1 hour');
IF agency.customer_session_list(other,u,'current')<>'[]'::jsonb THEN RAISE EXCEPTION 'Cross tenant sessions'; END IF;
SELECT x->>'id' INTO sid FROM jsonb_array_elements(agency.customer_session_list(t,u,'current')) x WHERE NOT (x->>'current')::boolean;
IF agency.customer_session_revoke(t,u,'current',sid)<>'revoked' THEN RAISE EXCEPTION 'Session not revoked'; END IF;
IF jsonb_array_length(agency.customer_session_list(t,u,'current'))<>1 THEN RAISE EXCEPTION 'Current session affected'; END IF;
FOR i IN 1..20 LOOP IF NOT agency.membership_request_allowed(t,'test-client') THEN RAISE EXCEPTION 'Early rate limit'; END IF; END LOOP;
IF agency.membership_request_allowed(t,'test-client') THEN RAISE EXCEPTION 'Rate limit bypass'; END IF;
IF agency.admin_mfa_begin(t,u,'long-test-password','test',ARRAY['hash'])<>'forbidden' THEN RAISE EXCEPTION 'Customer MFA administration'; END IF;
IF agency.admin_mfa_begin(t,a,'long-test-password','test',ARRAY[encode(digest('recovery','sha256'),'hex')])<>'pending' THEN RAISE EXCEPTION 'MFA enroll failed'; END IF;
IF NOT agency.admin_mfa_claim(t,a,10,'') OR agency.admin_mfa_claim(t,a,10,'') THEN RAISE EXCEPTION 'TOTP replay'; END IF;
IF agency.admin_mfa_claim(other,a,11,'') THEN RAISE EXCEPTION 'Cross tenant MFA'; END IF;
IF NOT agency.admin_mfa_claim(t,a,-1,'recovery') OR agency.admin_mfa_claim(t,a,-1,'recovery') THEN RAISE EXCEPTION 'Backup replay'; END IF;
FOR i IN 1..5 LOOP IF NOT agency.admin_mfa_attempt(t,a) THEN RAISE EXCEPTION 'Early MFA limit'; END IF; END LOOP;
IF agency.admin_mfa_attempt(t,a) THEN RAISE EXCEPTION 'MFA brute force'; END IF;
END $$;
ROLLBACK;
